set number
set encoding=UTF-8
set hidden
filetype plugin on
filetype plugin indent on
set nocompatible
set wildmenu
syntax on
set cursorline
set nowrap
set incsearch
set ignorecase
set smartcase
set showmatch
set hlsearch
set wildignore=*.docx,*.jpg,*.png,*.gif,*.pdf,*.pyc,*.exe,*.flv,*.img,*.xlsx





let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#left_sep = ' '
let g:airline#extensions#tabline#left_alt_sep = '|'
let g:airline#extensions#tabline#formatter = 'default'



call plug#begin()
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'flazz/vim-colorschemes'
Plug 'scrooloose/nerdtree'
Plug 'rust-lang/rust.vim'
Plug 'vimwiki/vimwiki'
Plug 'vim-ctrlspace/vim-ctrlspace'
Plug 'dense-analysis/ale'
call plug#end()

:map <C-n> :NERDTree
